# Generated by Django 5.0.4 on 2024-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0002_alter_order_table_alter_orderitem_table_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
    ]
